version: '2'

services:
        nginx:
                image: nginx
                ports:
                        - 8051:80
                volumes:
                        - ./nginx:/etc/nginx/
                restart: always
        splash:
                image: scrapinghub/splash
                ports:
                        - 8050:8050
                restart: always
